services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: coralbricks-backend-dev
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
      - PORT=3010
      - JWT_SECRET=${JWT_SECRET:-dev-secret-key-change-in-production}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-24h}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - QBO_CLIENT_ID=${QBO_CLIENT_ID}
      - QBO_CLIENT_SECRET=${QBO_CLIENT_SECRET}
      - QBO_AUTH_URL=${QBO_AUTH_URL:-https://appcenter.intuit.com/connect/oauth2}
      - QBO_REDIRECT_URI=${QBO_REDIRECT_URI:-http://localhost:3010/auth/quickbooks/callback}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3010}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - LOG_FILE=logs/auth-service.log
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/src:/app/src
      - ./common_js/src:/app/common_js/src
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3010/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - coralbricks-network

  chat-js:
    build:
      context: .
      dockerfile: chat_js/Dockerfile.dev
    container_name: coralbricks-chat-dev
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - LOG_FILE=logs/chat-service.log
    volumes:
      - ./chat_js/logs:/app/logs
      - ./chat_js/src:/app/src
      - ./common_js/src:/app/common_js/src
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3004/api/status', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - coralbricks-network
    depends_on:
      backend:
        condition: service_healthy

networks:
  coralbricks-network:
    driver: bridge
